import 'dart:ui';
import 'package:flutter/material.dart';

String _appTheme = "primary";                                                              // mod dark

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          disabledBackgroundColor: appTheme.blueGray300,
          backgroundColor: appTheme.indigoA700,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: appTheme.blueGray300.withOpacity(0.5),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {

  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 18,                                                                         //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w300,
        ),
        bodyMedium: TextStyle(
          color: appTheme.whiteA700.withOpacity(0.8),
          fontSize: 14,                                                                    //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray100.withOpacity(0.6),
          fontSize: 11,                                                                //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: appTheme.gray100,
          fontSize: 24,                                                                  //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: appTheme.gray100,
          fontSize: 12,                                                                   //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        labelMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 10,                                                                     //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 23,                                                                 //modify
          fontFamily: 'Signature',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 18,                                                                //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 14,                                                                //modify
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF6C63FF),
    primaryContainer: Color(0XFF232426),
    secondary: Color(0XFF232426),
    secondaryContainer: Color(0XFF6C63FF),
    tertiary: Color(0XFF232426),
    tertiaryContainer: Color(0XFF6C63FF),

    // Background colors
    background: Color(0XFF232426),

    // Surface colors
    surface: Color(0XFF232426),
    surfaceTint: Color(0XFF232426),
    surfaceVariant: Color(0XFF6C63FF),

    // Error colors
    error: Color(0XFF232426),
    errorContainer: Color(0XFF6C63FF),
    onError: Color(0XFFE6E6E6),
    onErrorContainer: Color(0XFF232426),

    // On colors(text colors)
    onBackground: Color(0XFFE6E6E6),
    onInverseSurface: Color(0XFFE6E6E6),
    onPrimary: Color(0XFF232426),
    onPrimaryContainer: Color(0XFFE6E6E6),
    onSecondary: Color(0XFFE6E6E6),
    onSecondaryContainer: Color(0XFF232426),
    onTertiary: Color(0XFFE6E6E6),
    onTertiaryContainer: Color(0XFF232426),

    // Other colors
    outline: Color(0XFF232426),
    outlineVariant: Color(0XFF232426),
    scrim: Color(0XFF232426),
    shadow: Color(0XFF232426),

    // Inverse colors
    inversePrimary: Color(0XFF232426),
    inverseSurface: Color(0XFF232426),

    // Pending colors
    onSurface: Color(0XFFE6E6E6),
    onSurfaceVariant: Color(0XFF232426),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blackf
  Color get black9003f => Color(0X3F000000);

  // BlueGray
  Color get blueGray300 => Color(0XFF949FA6);
  Color get blueGray400 => Color(0XFF888888);

  // Gray
  Color get gray100 => Color(0XFFF2F2F2);
  Color get gray600 => Color(0XFF666D73);
  Color get gray800 => Color(0XFF404040);
  Color get gray80001 => Color(0XFF363E40);
  Color get gray80002 => Color(0XFF484848);

  // Indigo
  Color get indigoA700 => Color(0XFF3D31FF);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
